# -*- mode: ruby -*-
# vi: set ft=ruby :
#
## Windows "Workstation" VM, sometimes Windows is needed, especially for IPMI-KVMs
#

Vagrant.configure("2") do |config|
  config.vm.box = "mwrock/Windows2016"
  ## Windows 7
  # config.vm.box = "datacastle/windows7"

  
  # config.vm.network "forwarded_port", guest: 80, host: 8080
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # config.vm.synced_folder "../data", "/vagrant_data"

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true
    # Customize the amount of memory on the VM:
    vb.memory = "2048"
  end
  config.vm.provision "bootstrap_choco", type: "shell", path: "https://chocolatey.org/install.ps1"
  config.vm.provision "install_tools", type: "shell", inline: <<-SHELL
    $env:Path += ";$ProgramData\\Chocolatey"

 choco feature enable -n allowGlobalConfirmation


    choco install 7zip.install
    choco install citrix-workspace
    choco install firefox
    choco install git.install
    choco install google-drive-file-stream
    choco install googlechrome
    choco install javaruntime
    choco install putty.install
    choco install slack
    choco install sysinternals
    choco install vcredist140
    choco install vcredist2015
    choco install vcxsrv
    choco install vscode
    choco install vim
    choco install vnc-viewer
    choco install webex
    choco install lens
    choco install adobereader
    choco install keepassxc
    choco install multipass
    choco install openvpn-connect
    choco install python
    choco install microsoft-windows-terminal
    choco install wireshark
    choco install yubikey-manager
    choco install zoom

    ## Requires reboot
    choco install wsl
    choco install wsl-ubuntu-2004

    choco feature disable -n allowGlobalConfirmation
  SHELL

end
